@startuml
(FeGSite) <-- [Service:Termine]
(FeGSite) <-- [Service:Predigten]
(FeGSite) <- [Service:Losungen]
(FeGSite) <- [Service:Artikel]
(FeGSite) <- [Service:Media]
[Service:Predigten] <-- [Service:Bibel]
[Service:Losungen] <-- [Service:Bibel]
[Service:Predigten] <-- [Service:Menschen]
[Service:Termine] <-- [Service:Menschen]
[Service:Artikel] <-- [Service:Menschen]
(Admin) -> [Service:Termine]
(Admin) -> [Service:Predigten]
(Admin) -> [Service:Losungen]
(Admin) -> [Service:Artikel]
(Admin) -> [Service:Media]
(Admin) -> [Service:Bibel]
(Admin) -> [Service:Menschen]
@enduml